### ISSUE TITLE
[Compatibility Request] Scrapper with CraftTweaker support?

### ISSUE THREAD

**Issue by Landiie** [elseytd/TheAurorian#16]
Would be super awesome, so packmakers could add their own armors to scrap with specified outputs! would make the gems a ton more useful <3

**Comment by shiroroku** [comment]
[the scrapper already has crafttweaker support ](https://github.com/elseytd/TheAurorian/blob/master/TheAurorian/src/main/java/com/elseytd/theaurorian/Compat/CraftTweaker/Scrapper_CraftTweaker.java)

its the same functions as moonlight forge but only as 1 input and 1 output. `mods.theaurorian.Scrapper;`

**Comment by Landiie** [comment]
Oh wow really? It isnt updated on your wiki, I never know :o cool!

![image](https://user-images.githubusercontent.com/43101146/91271236-b6d2c680-e72e-11ea-86cf-2cc7a0f5edb4.png)
