### ISSUE TITLE
Biome names not following vanilla format.

### ISSUE THREAD

**Issue by Duatao7055** [elseytd/TheAurorian#20]
I mean, the biome names are aurorianforest, aurorianforesthills, etc. while vanilla's biome names are like Mesa and Extreme Hills. Could you make your biome names match this? I'm using a mod that makes biome names pop up on screen as I walk into them, which makes this an issue.

**Comment by shiroroku** [comment]
got it https://github.com/elseytd/TheAurorian/commit/9957f291edc357e24c3d09223a288d734f21309b

**Comment by Duatao7055** [comment]
Thanks
