### ISSUE TITLE
Bane of Arthopods Should Work on the Spiders/Boss

### ISSUE THREAD

**Issue by Hydraheads** [elseytd/TheAurorian#26]
**What your suggestion is**
Bane of Arthropods enchantment should extend to the spider and spider mother

**Why is it a good suggestion?**
Bane of Arthropods is a useless enchant, and since this spider boss can be pretty difficult, it would be nice if the sword enchant was given purpose for this fight.

**Additional details**
I am playing the 1.12.2 version.

**Comment by shiroroku** [comment]
https://github.com/elseytd/TheAurorian/commit/89a42873f489826cfa57c4edbca91fb0e2e6189f

also added undead attributes to other mobs for dealing bonus damage to undead (like other mods silver weapons)
