### ISSUE TITLE
Chinese Language file for the latest mod version

### ISSUE THREAD

**Issue by GoldenTotem** [elseytd/TheAurorian#27]
**What your suggestion is**
A clear and concise description of what your idea is.
The Chinese Language file for the aurorain-mar2321. Updated by the original Chinese file.

**Why is it a good suggestion?**
Reasoning why you think its a good idea and how it would affect the mod.
The original Chinese file is too old, the new version is not supported, and there are some minor problems

**Additional details**
Any extra details to add
Here is the content of the file.

`
container.theaurorian.moonlightforge=月光融锻
container.theaurorian.scrapper=粉碎器

enchantment.theaurorian.lightning.desc=根据对方穿戴的护甲数量造成额外伤害
enchantment.theaurorian.lightning=雷电
enchantment.theaurorian.lightningresistance.desc=降低“雷电”魔咒造成的额外伤害，同时完全抵消被雷击中的伤害
enchantment.theaurorian.lightningresistance=雷电抵御

entity.theaurorian.aurorianpig.name=极光猪
entity.theaurorian.aurorianrabbit.name=极光兔
entity.theaurorian.auroriansheep.name=极光羊
entity.theaurorian.aurorianslime.name=极光史莱姆
entity.theaurorian.crystallinesprite.name=月凝晶魂
entity.theaurorian.disturbedhollow.name=空谷之扰
entity.theaurorian.moonacolyte.name=皎月侍从
entity.theaurorian.moonqueen.name=皎月女王
entity.theaurorian.runestonedungeonkeeper.name=符石守卫
entity.theaurorian.spider.name=蛛母
entity.theaurorian.spiderling.name=幼蛛
entity.theaurorian.spirit.name=魂灵
entity.theaurorian.undeadknight.name=不死骑士

fluid.tamoltenauroriansteel=熔融极光钢
fluid.tamoltencerulean=熔融晶蓝
fluid.tamoltenmoonstone=熔融皎月石
fluid.tamoonwater=月露

item.theaurorian.absorptionorb.name=修复宝珠
item.theaurorian.aurorianbacon.name=极光培根
item.theaurorian.auroriancoal.name=极光煤炭
item.theaurorian.auroriancoalnugget.name=极光煤炭粒
item.theaurorian.aurorianiteaxe.name=极光斧
item.theaurorian.aurorianiteingot.name=极光锭
item.theaurorian.aurorianitepickaxe.name=极光镐
item.theaurorian.aurorianitesword.name=极光剑
item.theaurorian.aurorianpork.name=生极光猪排
item.theaurorian.aurorianporkcooked.name=熟极光猪排
item.theaurorian.aurorianportalframebrick.name=极光砖
item.theaurorian.aurorianslimeball.name=极光粘液球
item.theaurorian.aurorianslimeboots.name=极光粘液靴子
item.theaurorian.auroriansteel.name=极光钢锭
item.theaurorian.auroriansteelaxe.name=极光钢斧
item.theaurorian.auroriansteelboots.name=极光钢靴子
item.theaurorian.auroriansteelchestplate.name=极光钢胸甲
item.theaurorian.auroriansteelhelmet.name=极光钢头盔
item.theaurorian.auroriansteelhoe.name=极光钢锄
item.theaurorian.auroriansteelleggings.name=极光钢护腿
item.theaurorian.auroriansteelnugget.name=极光钢粒
item.theaurorian.auroriansteelpickaxe.name=极光钢镐
item.theaurorian.auroriansteelshovel.name=极光钢铲
item.theaurorian.auroriansteelsword.name=极光钢剑
item.theaurorian.aurorianstoneaxe.name=极光石斧
item.theaurorian.aurorianstonehoe.name=极光石锄
item.theaurorian.aurorianstonepickaxe.name=极光石镐
item.theaurorian.aurorianstoneshovel.name=极光石铲
item.theaurorian.aurorianstonesickle.name=极光石镰
item.theaurorian.aurorianstonesword.name=极光石剑
item.theaurorian.bepsi.name=旦事可乐
item.theaurorian.ceruleanarrow.name=晶蓝箭
item.theaurorian.ceruleanboots.name=晶蓝靴子
item.theaurorian.ceruleanbucket.filled.name=%s晶蓝桶
item.theaurorian.ceruleanbucket.name=晶蓝桶
item.theaurorian.ceruleanchestplate.name=晶蓝胸甲
item.theaurorian.ceruleanhelmet.name=晶蓝头盔
item.theaurorian.ceruleaningot.name=晶蓝锭
item.theaurorian.ceruleanleggings.name=晶蓝护腿
item.theaurorian.ceruleannugget.name=晶蓝粒
item.theaurorian.ceruleanshield.name=晶蓝盾牌
item.theaurorian.crystallineingot.name=月凝晶锭
item.theaurorian.crystallinepickaxe.name=月凝晶镐
item.theaurorian.crystallineshield.name=月凝晶盾牌
item.theaurorian.crystallinesword.name=月凝晶剑
item.theaurorian.cup.name=杯子
item.theaurorian.darkamulet.name=暗黑护符
item.theaurorian.darkstonekey.name=暗石钥匙
item.theaurorian.debugger.name=调试器
item.theaurorian.keeperamulet.name=地牢守卫护身符
item.theaurorian.keepersbow.name=守卫之弓
item.theaurorian.knightboots.name=骑士靴子
item.theaurorian.knightchestplate.name=骑士胸甲
item.theaurorian.knighthelmet.name=骑士头盔
item.theaurorian.knightleggings.name=骑士护腿
item.theaurorian.lavender.name=薰衣草
item.theaurorian.lavenderbread.name=薰衣草面包
item.theaurorian.lavenderseeds.name=薰衣草籽
item.theaurorian.livingdiviningrod.name=生命卜窥权杖
item.theaurorian.locator.name=地牢定位器
item.theaurorian.lockpicks.name=开锁器
item.theaurorian.moonshield.name=皎月之盾
item.theaurorian.moonstoneaxe.name=皎月石斧
item.theaurorian.moonstonehoe.name=皎月石锄
item.theaurorian.moonstoneingot.name=皎月石锭
item.theaurorian.moonstonenugget.name=皎月石粒
item.theaurorian.moonstonepickaxe.name=皎月石镐
item.theaurorian.moonstoneshield.name=皎月石盾牌
item.theaurorian.moonstoneshovel.name=皎月石铲
item.theaurorian.moonstonesickle.name=皎月石镰
item.theaurorian.moonstonesword.name=皎月石剑
item.theaurorian.moontemplecellkey.name=月宫内室钥匙
item.theaurorian.moontemplecellkeyfragment.name=月宫内室钥匙碎片
item.theaurorian.moontemplekey.name=月宫钥匙
item.theaurorian.plantfiber.name=植物纤维
item.theaurorian.queenschipper.name=女王镐
item.theaurorian.runestonekey.name=符石钥匙
item.theaurorian.runestonelootkey.name=符石宝藏钥匙
item.theaurorian.scrapaurorianite.name=极光碎片
item.theaurorian.scrapcrystalline.name=月凝晶碎片
item.theaurorian.scrapumbra.name=本影碎片
item.theaurorian.silentwoodaxe.name=谧木斧
item.theaurorian.silentwoodbow.name=谧木弓
item.theaurorian.silentwoodhoe.name=谧木锄
item.theaurorian.silentwoodpickaxe.name=谧木镐
item.theaurorian.silentwoodshovel.name=谧木铲
item.theaurorian.silentwoodsickle.name=谧木镰
item.theaurorian.silentwoodstick.name=谧木棍
item.theaurorian.silentwoodsword.name=谧木剑
item.theaurorian.silkberry.name=桑葚
item.theaurorian.silkberryjam.name=桑葚酱
item.theaurorian.silkberryjamsandwich.name=桑葚酱三明治
item.theaurorian.silkshroomstew.name=桑葚煲
item.theaurorian.soullessflesh.name=魂灭之肉
item.theaurorian.spectralsilk.name=幽冥丝绸
item.theaurorian.spectralboots.name=幽冥靴子
item.theaurorian.spectralchestplate.name=幽冥胸甲
item.theaurorian.spectralhelmet.name=幽冥头盔
item.theaurorian.spectralleggings.name=幽冥护腿
item.theaurorian.spikedchestplate.name=尖钉胸甲
item.theaurorian.stickyspiker.name=粘性尖钉
item.theaurorian.strangemeat.name=怪异的肉
item.theaurorian.tealavender.name=薰衣草茶
item.theaurorian.teapetunia.name=牵牛花茶
item.theaurorian.teaseedy.name=薰衣草籽茶
item.theaurorian.teasilkberry.name=桑葚茶
item.theaurorian.trophykeeper.name=符石地牢守卫奖励
item.theaurorian.trophymoonqueen.name=皎月女王奖励
item.theaurorian.trophyspider.name=蛛母奖励
item.theaurorian.umbraingot.name=本影锭
item.theaurorian.umbrapickaxe.name=本影镐
item.theaurorian.umbrashield.name=本影盾牌
item.theaurorian.umbrasword.name=本影剑
item.theaurorian.weepingwillowsap.name=垂柳木树液

itemGroup.theaurorian=极光幽境

material.auroriansteel.name=极光钢
material.aurorianstone.name=极光石
material.cerulean.name=晶蓝
material.moonstone.name=皎月石
material.silentwood.name=谧木

modifier.aurorianempowered.desc=§o极光涌流之力！§r\n在极光幽境中工具速度更快。！
modifier.aurorianempowered.name=极光之赐
modifier.conarmmoonlit_armor.desc=§o它是个夜猫子！§r\n在夜晚有 50% 的机会不消耗耐久，但在白天有 50% 的机会消耗更多耐久！
modifier.conarmmoonlit_armor.name=月辉
modifier.tamoonlit.desc=§o它是个夜猫子！§r\n在夜晚有 50% 的机会不消耗耐久，但在白天有 50% 的机会消耗更多耐久！
modifier.tamoonlit.name=月辉

string.theaurorian.block.dungeonstonekeyhole1=我需要一把钥匙
string.theaurorian.block.dungeonstonekeyhole2=或者一个开锁器
string.theaurorian.gui.moonlightforge.nomoonlight=没有检测到月光！
string.theaurorian.gui.moonlightforge.redstone=目前已被红石信号禁用。
string.theaurorian.item.locator1=已定位符石地牢
string.theaurorian.item.locator2=已定位月宫
string.theaurorian.item.locator3=已定位暗石地牢
string.theaurorian.tooltip.absorptionorb=在副手时会修复你主手持握的物品！
string.theaurorian.tooltip.amuletdark=恐惧之息细微弥漫……用于制作月宫钥匙。
string.theaurorian.tooltip.amuletkeeper=腐败之力在蠢蠢欲动，用于制作暗石钥匙。
string.theaurorian.tooltip.aurorianbacon=虽泛紫意，但鲜嫩多汁！
string.theaurorian.tooltip.aurorianiteaxe=可以砍倒整棵树！
string.theaurorian.tooltip.aurorianitepickaxe=越挖越快！
string.theaurorian.tooltip.aurorianitesword=让周围的人与我一同失重！
string.theaurorian.tooltip.aurorianporkcooked=虽泛紫意，但鲜嫩多汁！
string.theaurorian.tooltip.aurorianslimeboots=潜行时起跳可以跳得更高，并且还能消除摔落伤害。
string.theaurorian.tooltip.auroriansteeltools=随着时间的推移，此物品上的附魔会升级！
string.theaurorian.tooltip.auroriansteeltools.nextenchant=下一附魔：
string.theaurorian.tooltip.auroriansteeltools.noenchants=没有找到附魔，或者附魔已为满级！
string.theaurorian.tooltip.aurorianstoneaxe=以消耗额外的耐久为代价，砍倒整棵谧木树！
string.theaurorian.tooltip.aurorianstonepickaxe=开采极光石时，有机会恢复自身耐久。
string.theaurorian.tooltip.bepsi=哪来的山寨货？？
string.theaurorian.tooltip.crystal=放置在粉碎器旁可为其加速！有一定几率直接分解所有物品。
string.theaurorian.tooltip.crystallinepickaxe=矿石不仅会掉落矿物锭，还会额外附赠一些矿粒！
string.theaurorian.tooltip.crystallineshield=完成抵挡后修复你的主手物品！
string.theaurorian.tooltip.crystallinesword=充能！发射水晶光束！
string.theaurorian.tooltip.dungeonstonegate1=在门锁孔所在的 x 轴或 z 轴上最多能放置
string.theaurorian.tooltip.dungeonstonegate2=个方块！
string.theaurorian.tooltip.furnacechimney1=当放在极光熔炉上时，它会加快熔炼速度！每炉最大孔道数为
string.theaurorian.tooltip.furnacechimney2=个。右击带有孔道的熔炉，它们会自动堆叠在顶部。
string.theaurorian.tooltip.keepersbow=完全充能后自动一次性射出三支箭矢！
string.theaurorian.tooltip.keydarkstone=用来解锁禁地……
string.theaurorian.tooltip.keymoontemple=用来开启月宫大门，只能使用一次！
string.theaurorian.tooltip.keymoontemplecell=用来开启月宫内室，只能使用一次!
string.theaurorian.tooltip.keyrunestone=用来开启符石大门，只能使用一次！
string.theaurorian.tooltip.keyrunestoneloot=用来开启符石地牢宝藏室。
string.theaurorian.tooltip.lavender=通过破坏薰衣草获得，或者自己种植。
string.theaurorian.tooltip.lavenderseeds=在工作台上使用薰衣草制作。
string.theaurorian.tooltip.livingdiviningrod=有一定几率使周围实体发光！
string.theaurorian.tooltip.locator=可用于定位周围的极光幽境地牢。
string.theaurorian.tooltip.locator=用来定位地牢，潜行右击可以切换模式，需要打开粒子效果显示！
string.theaurorian.tooltip.lockpicks=用来开启符石地牢，高概率损坏。
string.theaurorian.tooltip.moongem=可在月宫柱岛找到这种宝石，用于制作月宫钥匙。
string.theaurorian.tooltip.moonshield=右击蓄能，然后将敌人狠狠地击飞到空中！
string.theaurorian.tooltip.moonstonetools=皎月石与月同在！在夜晚消耗更少耐久，在白天消耗更多耐久。
string.theaurorian.tooltip.moontemplecellkeyfragment=用于制作月宫内室钥匙。
string.theaurorian.tooltip.moontorch=赞助者物品：Antonio P(安东尼奥 P)
string.theaurorian.tooltip.mushroom=弹弹弹！
string.theaurorian.tooltip.plantfiber=用镰破坏极光高草丛获得。
string.theaurorian.tooltip.portalframebricks=用于制作极光传送门。像建造下界传送门一样建造它，并用打火石点亮！
string.theaurorian.tooltip.queenschipper=右击可以破坏原本无法破坏的地牢组成方块。
string.theaurorian.tooltip.shiftinfo=按住Shift键获取更多信息
string.theaurorian.tooltip.silentwoodaxe=神奇的谧木工具在砍伐谧木时，有机会恢复自己的耐久！
string.theaurorian.tooltip.silentwoodpickaxe1=当前等级：
string.theaurorian.tooltip.silentwoodpickaxe2=神奇的谧木工具在耐久度低时会提高挖掘等级！
string.theaurorian.tooltip.silentwoodstick=可以用来点火，也可以用来点亮极光传送门。
string.theaurorian.tooltip.silkberryjamsandwich=味道好极了！
string.theaurorian.tooltip.spectralarmor=有 %s 几率在攻击时净化身上的负面效果！
string.theaurorian.tooltip.spectralsilk=由灵所凝。
string.theaurorian.tooltip.spikedchestplate=在潜行时获得荆棘 III。
string.theaurorian.tooltip.stickyspiker=使命中的实体中毒。
string.theaurorian.tooltip.strangemeat=这么大一块肉，可有得一阵好嚼了！吃完之后获得一种随机的正面效果。
string.theaurorian.tooltip.umbrapickaxe=选择一种方块，对它进行挖掘的速度会有所提高，但是选择这一过程会减少大量耐久度。
string.theaurorian.tooltip.umbrashield=在抵挡攻击状态下时会点燃正前方的实体。抵挡时间过长会过载！
string.theaurorian.tooltip.umbrasword=以虚弱和缓慢的效果为代价，给予你两个短暂的对生命值恢复有帮助的效果！
string.theaurorian.tooltip.weepingwillowsap=去除你的中毒效果，但却会使你获得缓慢效果。

tile.tamoonwater.name=月露
tile.theaurorian.auroriancoalblock.name=极光煤炭块
tile.theaurorian.auroriancoalore.name=极光煤矿石
tile.theaurorian.auroriancobblestone.name=极光圆石
tile.theaurorian.auroriancobblestonestairs.name=极光圆石楼梯
tile.theaurorian.auroriandirt.name=极光泥土
tile.theaurorian.aurorianfarmtile.name=极光农砖
tile.theaurorian.aurorianfurnace.name=极光熔炉
tile.theaurorian.aurorianfurnacechimney.name=极光熔炉孔道
tile.theaurorian.aurorianglass.name=极光玻璃
tile.theaurorian.aurorianglasspane.name=极光玻璃板
tile.theaurorian.auroriangrass.name=极光草
tile.theaurorian.auroriangrasslight.name=发光极光草
tile.theaurorian.aurorianperidotite.name=极光橄榄岩
tile.theaurorian.aurorianperidotitesmooth.name=平滑极光橄榄岩
tile.theaurorian.aurorianperidotitesmoothstairs.name=平滑橄榄岩楼梯
tile.theaurorian.aurorianportalframebricks.name=极光传送门框架
tile.theaurorian.auroriansteelblock.name=极光钢块
tile.theaurorian.aurorianstone.name=极光石
tile.theaurorian.aurorianstonebrick.name=极光石砖
tile.theaurorian.aurorianstonestairs.name=极光石砖楼梯
tile.theaurorian.auroriantallgrass.name=极光高草丛
tile.theaurorian.auroriantallgrasslight.name=发光极光高草丛
tile.theaurorian.bossspawnerkeeper.name=生成 符石守卫
tile.theaurorian.bossspawnermoonqueen.name=生成 月光女王
tile.theaurorian.bossspawnerspider.name=生成 蛛母
tile.theaurorian.ceruleanblock.name=晶蓝块
tile.theaurorian.ceruleanore.name=晶蓝矿石
tile.theaurorian.crystal.name=水晶
tile.theaurorian.darkstonebricks.name=暗石砖块
tile.theaurorian.darkstonefancy.name=装饰性暗石
tile.theaurorian.darkstonegate.name=暗石门
tile.theaurorian.darkstonegatekeyhole.name=暗石门锁孔
tile.theaurorian.darkstonelamp.name=暗石灯
tile.theaurorian.darkstonelayers.name=暗石地层
tile.theaurorian.darkstonestairs.name=暗石楼梯
tile.theaurorian.geodeore.name=晶簇矿石
tile.theaurorian.lavenderplant.name=薰衣草
tile.theaurorian.moongem.name=皎月宝石
tile.theaurorian.moonglass.name=皎月玻璃
tile.theaurorian.moonglasspane.name=皎月玻璃板
tile.theaurorian.moonlightforge.name=月光融锻台
tile.theaurorian.moonsand.name=皎月沙
tile.theaurorian.moonstoneblock.name=皎月石块
tile.theaurorian.moonstoneore.name=皎月石矿石
tile.theaurorian.moontemplebars.name=月宫栏杆
tile.theaurorian.moontemplebricks.name=月宫砖块
tile.theaurorian.moontemplebrickssmooth.name=平滑月宫砖块
tile.theaurorian.moontemplecellgate.name=月宫内室门
tile.theaurorian.moontemplecellgatekeyhole.name=月宫内室门锁孔
tile.theaurorian.moontemplegate.name=月宫门
tile.theaurorian.moontemplegatekeyhole.name=月宫门锁孔
tile.theaurorian.moontemplelamp.name=月宫灯
tile.theaurorian.moontemplestairs.name=月宫楼梯
tile.theaurorian.moontorch.name=月之火把
tile.theaurorian.mushroom.name=深蓝蘑菇
tile.theaurorian.mushroomcrystal.name=蘑菇水晶
tile.theaurorian.mushroomsmall.name=深蓝蘑菇
tile.theaurorian.mushroomstem.name=深蓝蘑菇茎
tile.theaurorian.mysticalbarrier.name=神秘屏障
tile.theaurorian.petuniaplant.name=牵牛花
tile.theaurorian.runestone.name=符石
tile.theaurorian.runestonebars.name=符石栏杆
tile.theaurorian.runestonegate.name=符石门
tile.theaurorian.runestonegatekeyhole.name=符石门锁孔
tile.theaurorian.runestonelamp.name=符石灯
tile.theaurorian.runestonelootgate.name=符石宝藏室门
tile.theaurorian.runestonelootgatekeyhole.name=符石宝藏室门锁孔
tile.theaurorian.runestonesmooth.name=平滑符石
tile.theaurorian.runestonestairs.name=符石楼梯
tile.theaurorian.scrapper.name=粉碎器
tile.theaurorian.silentwoodchest.name=谧木箱子
tile.theaurorian.silentwoodcraftingtable.name=谧木工作台
tile.theaurorian.silentwoodladder.name=谧木梯子
tile.theaurorian.silentwoodleaves.name=谧树树叶
tile.theaurorian.silentwoodlog.name=谧木
tile.theaurorian.silentwoodplanks.name=谧木木板
tile.theaurorian.silentwoodsapling.name=谧树树苗
tile.theaurorian.silentwoodstairs.name=谧木楼梯
tile.theaurorian.silentwoodtorch.name=谧木火把
tile.theaurorian.silkberryplant.name=桑葚植株
tile.theaurorian.umbrastone.name=本影石
tile.theaurorian.umbrastonecracked.name=裂纹本影石
tile.theaurorian.umbrastoneroofstairs.name=本影石瓦楼梯
tile.theaurorian.umbrastonerooftiles.name=本影石瓦
tile.theaurorian.urn.name=瓮
tile.theaurorian.weepingwillowleaves.name=垂柳树叶
tile.theaurorian.weepingwillowlog.name=垂柳木
tile.theaurorian.weepingwillowplanks.name=垂柳木板
tile.theaurorian.weepingwillowplanksstairs.name=垂柳木楼梯
tile.theaurorian.weepingwillowsapling.name=垂柳树苗

patchouli.theaurorian.guide.name=极光幽境指南
patchouli.theaurorian.guide.desc=包含了模组的全部内容，并且提供了游玩指引。
`

**Comment by shiroroku** [comment]
thank you for the translation
https://github.com/elseytd/TheAurorian/commit/aab8a707a69414885ca584bd7adfffa4af8683b9
