### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by axin0452** [elseytd/TheAurorian#28]
An error occurs when you right-click RUNESTONE GATE KEYHOLE with your bare hands 

https://paste.ubuntu.com/p/5NTpnNT8SR/

theaurorian-1.12.2-release-mar2321

This server is running CatServer version git-CatServer-1.12.2-4292748 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855

**Comment by shiroroku** [comment]
https://github.com/elseytd/TheAurorian/commit/825e85c79f4dc9af1d66ed4b2b0bd068459429ab
