### ISSUE TITLE
No biome types

### ISSUE THREAD

**Issue by hoolatehip** [elseytd/TheAurorian#30]
Aurorian biomes lack biome types. This may cause compatibility issues with mods that rely on biome types to add their own features. 

**Versions/Environtment**
- Aurorian Version: Release-May0521
- Custom modpack

Log excerpt: 

> [21:52:57] [Client thread/WARN] [FML]: No types have been added to Biome theaurorian:aurorianforest, types have been assigned on a best-effort guess: [PLAINS]
> [21:52:57] [Client thread/WARN] [FML]: No types have been added to Biome theaurorian:aurorianforesthills, types have been assigned on a best-effort guess: [PLAINS]
> [21:52:57] [Client thread/WARN] [FML]: No types have been added to Biome theaurorian:aurorianplains, types have been assigned on a best-effort guess: [PLAINS]
> [21:52:57] [Client thread/WARN] [FML]: No types have been added to Biome theaurorian:weepingwillowforest, types have been assigned on a best-effort guess: [HILLS]
> [21:52:57] [Client thread/WARN] [FML]: No types have been added to Biome theaurorian:aurorianlakes, types have been assigned on a best-effort guess: [PLAINS]

Beautiful mod, by the way. Thanks for your hard work.

**Comment by shiroroku** [comment]
aurorian biomes do have types, but not those ones. they have cold, dry, and magical. but ill add those types also.
currently my ide's are bugged and im working on fixing them so i can fix this and push out an update.
https://github.com/elseytd/TheAurorian/blob/eecb4226004a497f0eb2814eea7629877777e51b/TheAurorian/src/main/java/com/elseytd/theaurorian/TABiomes.java#L40

**Comment by hoolatehip** [comment]
Thank you!

**Comment by shiroroku** [comment]
https://github.com/elseytd/TheAurorian/commit/607b23c7beb5d6b39db3689763801462e7f60dd1
