### ISSUE TITLE
Recurrent Complex Compat bug

### ISSUE THREAD

**Issue by ElLiox** [elseytd/TheAurorian#32]
Recurrent Complex structures appear in The Aurorian dimension

https://imgur.com/a/Xz70SRD

I consider it a bug because they collapse with the structures of The Aurorian both in aesthetics and gameplay
They should be disabled by default in the aurorian dimension

RecurrentComplex-1.4.8.2 &  theaurorian-1.12.2-release-may3021
1.12.2

**Comment by Ringedtech203** [comment]
idk if it can be done mod side but you can always just blacklist it in the RC config

**Comment by Ringedtech203** [comment]
![Capture](https://user-images.githubusercontent.com/44550133/142517946-782a68b2-4c7d-4e93-82bc-4a2c0a58ea60.PNG)
add !424 to the dimension expression to blacklist it
