### ISSUE TITLE
Compatability Request - Bonsai

### ISSUE THREAD

**Issue by Azuriuz** [elseytd/TheAurorian#5]
Hey there, I love this mod sofar and want to have it in my modpack. While playing with it, I've found the trees don't work with Bonsai.
While checking into mod compatibility sofar, I've learned basically you have to talk to the mod author and they can include your trees.
I hope you'll consider taking the time to look into compatibility, as I think it will give people more chances to enjoy the wood your mod offers for their builds, without causing deforestation lol!

For your convenience, I have their mod linked below. Thank you for taking the time to read this.
https://www.curseforge.com/minecraft/mc-mods/bonsai-trees

**Comment by shiroroku** [comment]
[I just did a pull request for Silentwood Trees compatibility on the Bonsai Git.](https://github.com/thraaawn/BonsaiTrees/pull/153)
Now waiting for them to accept it.

**Comment by Azuriuz** [comment]
Awesome! Thank you so much, I can't wait to grow silentwood in my bonsai pots!

**Comment by shiroroku** [comment]
the request was closed, sadly :c

**Comment by LonelyxiyaOVO** [comment]
It doesn't matter!I'll fork it because it's the MIT protocol.

**Comment by LonelyxiyaOVO** [comment]
It's better now![#5
](https://github.com/CanoeStudioOfficial/BonsaiTrees/commit/a107f97639713e1eb9c54c31086f3acce9cf0c53)
