### ISSUE TITLE
Same Dim ID As The Midnight

### ISSUE THREAD

**Issue by TheVisionaryOne** [elseytd/TheAurorian#6]
The Aurorian dimension has the same ID (24) as The Midnight dimension, which is a very popular mod with over 1M downloads currently. 

It's a small issue since users can change the dimension ID in the mod's config file if they know how, but if you want to make this mod more compatible for modpacks, it definitely wouldn't be a bad idea to change the dim ID.

**Comment by shiroroku** [comment]
Thanks, changed ID to 424.

https://github.com/elseytd/TheAurorian/commit/9dd526fc235c14f61f153de2305cb63721c84488
