### ISSUE TITLE
Incompatibility With Stupid Things Mod

### ISSUE THREAD

**Issue by TheVisionaryOne** [elseytd/TheAurorian#7]
I've experienced two crashes related to this mod being incompatible with Stupid Things, both in Creative.

First, I was hovering over a cerulean bucket of...something in creative mode when it crashed. I believe Stupid Things adds liquid rubber into the game, so it was probably that. I guess the issue was with your code interacting with Stupid Things' code to try and make an Aurorian Cerulean bucket out of Stupid Things' liquid?

Second, I tried to read The Aurorian patchouli book, and it crashed while opening the book. I saw the book for a split-second, and then I crashed.

Both crashes' logs look nearly identical, but here they both are. They mention something about tooltip text and hovering over items.

1st Crash Log: https://paste.dimdev.org/arivuyolul.mccrash
2nd Crash Log: https://paste.dimdev.org/xemeqezowu.mccrash

**Comment by shiroroku** [comment]
Seems like a NullPointerException with their mod [right here](https://github.com/Furgl/Stupid-Things/blob/b7b3d1dd228f894dfac5a8ce807e4b99d36520b9/src/main/java/furgl/stupidThings/util/TooltipHelper.java#L76). I'm not sure what I can change to fix it at the moment.

**Comment by TheVisionaryOne** [comment]
Oh, you're right! I see a couple of comments on Stupid Things' CurseForge page complaining of other crashes, also caused by a NullPointerException. That has to be their problem. I guess I'll have to remove that mod from my pack then.

Edit: Apparently somebody found a fix to this problem by simply disabling acid and rubber from Stupid Things, so I won't have to get rid of the mod completely. That's good news.
