### ISSUE TITLE
Aurorian Slimes' Neat Health Bar Is Too High

### ISSUE THREAD

**Issue by TheVisionaryOne** [elseytd/TheAurorian#8]
This is a small bug, but for some reason, when using the Neat mod (which adds health bars to mobs), it places the Aurorian Slimes' health bars like 2 blocks above their body. It should normally be right above their body, less than a block away, but it's not that way for Aurorian Slimes.

Maybe it has something to do with the fact that slimes have different sizes, and Neat thinks that Aurorian Slimes are the biggest slime size, when in fact, they are the smallest?

![2020-04-16_13 25 46](https://user-images.githubusercontent.com/56095032/79504123-2b5e6180-7fe7-11ea-835b-3d8c42c2eb02.png)

Here's an example pic of the regular distance between a neat health bar and a mob:
![2019-11-10_19 27 33](https://user-images.githubusercontent.com/56095032/79504216-619be100-7fe7-11ea-878a-6f27f3edc9ca.png)

**Comment by shiroroku** [comment]
Thanks, should be fixed now.

https://github.com/elseytd/TheAurorian/commit/e29d397480e597c8ab3fbc976a3f5a5c12b0c641
