### ISSUE TITLE
Silkberry Raisin Typo?

### ISSUE THREAD

**Issue by TheVisionaryOne** [elseytd/TheAurorian#9]
This is the smallest bug I've found, but I believe there's a typo in the name for the Silkberry Raisin item. It's missing an "i," and is currently called the Silkberry...Rasin? Unless that's intentional, and you're inventing a new food for the Aurorian world, which is totally sick.

![2020-04-16_13 26 57](https://user-images.githubusercontent.com/56095032/79504270-7a0bfb80-7fe7-11ea-97b9-0480f55ec7f8.png)

**Comment by shiroroku** [comment]
It was a typo. Though I've been planning to remove it for a while now.

https://github.com/elseytd/TheAurorian/commit/04571df0bcb4543ed7e7660acb1d8ecb9693e65e
